# Generated by Django 3.2.5 on 2021-07-11 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attestationsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestations',
            name='document_under',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Срок действия документа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attestations',
            name='document_upload',
            field=models.FileField(blank=True, upload_to='attestations_documents', verbose_name='загрузить документ'),
        ),
    ]
