# Generated by Django 3.2.5 on 2021-07-11 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestationsapp', '0002_auto_20210711_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestations',
            name='document_upload',
            field=models.FileField(default=datetime.date(1, 1, 1), upload_to='attestations_documents', verbose_name='загрузить документ'),
        ),
    ]
