# Generated by Django 3.2.5 on 2021-07-13 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubstateapp', '0001_initial'),
        ('clubsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_meeting', models.DateField(verbose_name='Дата Заседания')),
                ('time_meeting', models.TimeField(verbose_name='Время')),
                ('case_number', models.CharField(max_length=128, unique=True, verbose_name='номер дела')),
                ('potential_art', models.CharField(max_length=128, verbose_name='Статьи нарушений')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('club_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubsapp.clubs', verbose_name='Клуб')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubstateapp.clubsstate', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Дело',
                'verbose_name_plural': 'Дела',
            },
        ),
    ]
