# Generated by Django 3.2.5 on 2021-07-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='bank_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Имя Банка'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='check_ac',
            field=models.CharField(blank=True, max_length=20, verbose_name='Расчетный счет'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='creat_club',
            field=models.FileField(blank=True, upload_to='<django.db.models.fields.CharField>', verbose_name='Создание'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='creat_rucovod',
            field=models.FileField(blank=True, upload_to='<django.db.models.fields.CharField>', verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='fact_addr',
            field=models.CharField(blank=True, max_length=128, verbose_name='Факт. Адрес'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='inn',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='jur_addr',
            field=models.CharField(blank=True, max_length=128, verbose_name='Офиц. Адрес'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='o_p_f',
            field=models.CharField(blank=True, max_length=128, verbose_name='Форма'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='ofice',
            field=models.FileField(blank=True, upload_to='<django.db.models.fields.CharField>', verbose_name='Офис'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='ogrn',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=13, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='reg_in_min_just',
            field=models.FileField(blank=True, upload_to='<django.db.models.fields.CharField>', verbose_name='МинЮст'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='reg_in_tax',
            field=models.FileField(blank=True, upload_to='<django.db.models.fields.CharField>', verbose_name='Налоговая'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='site',
            field=models.URLField(blank=True, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='ustav',
            field=models.FileField(blank=True, upload_to='<django.db.models.fields.CharField>', verbose_name='Устав'),
        ),
    ]
