# Generated by Django 3.2.5 on 2021-07-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubsapp', '0002_auto_20210711_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='creat_club',
            field=models.FileField(blank=True, upload_to='clubs_documents', verbose_name='Создание'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='creat_rucovod',
            field=models.FileField(blank=True, upload_to='clubs_documents', verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='inn',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='ofice',
            field=models.FileField(blank=True, upload_to='clubs_documents', verbose_name='Офис'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='ogrn',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=13, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='reg_in_min_just',
            field=models.FileField(blank=True, upload_to='clubs_documents', verbose_name='МинЮст'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='reg_in_tax',
            field=models.FileField(blank=True, upload_to='clubs_documents', verbose_name='Налоговая'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='ustav',
            field=models.FileField(blank=True, upload_to='clubs_documents', verbose_name='Устав'),
        ),
    ]
