# Generated by Django 3.2.5 on 2021-07-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubsapp', '0003_auto_20210711_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='status',
            field=models.CharField(choices=[('Допущен', 'Допущен до соревнования'), ('Не Допущен', 'Не допущен до соревнования')], default='Допущен', max_length=32),
        ),
    ]
