# Generated by Django 3.1.1 on 2021-07-12 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubsapp', '0006_auto_20210712_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='avatar',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='clubs_avatars', verbose_name='аватар'),
            preserve_default=False,
        ),
    ]
