# Generated by Django 3.2.5 on 2021-07-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stadiums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('shrt_name', models.CharField(max_length=128, unique=True, verbose_name='Сокращенное Название')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='почта')),
                ('o_p_f', models.CharField(blank=True, max_length=128, verbose_name='Форма')),
                ('jur_addr', models.CharField(blank=True, max_length=128, verbose_name='Офиц. Адрес')),
                ('fact_addr', models.CharField(blank=True, max_length=128, verbose_name='Факт. Адрес')),
                ('site', models.URLField(blank=True, verbose_name='Сайт')),
                ('inn', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='ИНН')),
                ('ogrn', models.DecimalField(decimal_places=0, default=0, max_digits=13, verbose_name='ОГРН')),
                ('bank_name', models.CharField(blank=True, max_length=128, verbose_name='Имя Банка')),
                ('check_ac', models.CharField(blank=True, max_length=20, verbose_name='Расчетный счет')),
                ('in_Reg_stad', models.FileField(blank=True, upload_to='stadiums_documents', verbose_name='Реестр Видов Спорта')),
                ('conf_in_expluatation', models.FileField(blank=True, upload_to='stadiums_documents', verbose_name='Ввод в эксплуатац')),
                ('instr_pub_order', models.FileField(blank=True, upload_to='stadiums_documents', verbose_name='Инструкция безопасности')),
                ('instr_pub_order_date_until', models.DateField(blank=True, verbose_name='Инструкция безопасности до')),
                ('act_categ', models.FileField(blank=True, upload_to='stadiums_documents', verbose_name='Акт категорирования')),
                ('act_categ_date_until', models.DateField(blank=True, verbose_name='Акт категорирования до')),
                ('statd_plan', models.FileField(blank=True, upload_to='stadiums_documents', verbose_name='План стадиона')),
                ('category_RFS', models.FileField(blank=True, upload_to='stadiums_documents', verbose_name='Категория РФС')),
                ('status', models.CharField(choices=[('Допущен', 'Допущен до соревнования'), ('Не Допущен', 'Не допущен до соревнования')], default='Допущен', max_length=32)),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'стадион',
                'verbose_name_plural': 'стадионы',
            },
        ),
    ]
