# Generated by Django 3.1.1 on 2021-07-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubstateapp', '0002_alter_clubsstate_licence_under'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubsstate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
