# Generated by Django 3.2.5 on 2021-07-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubstateapp', '0003_auto_20210712_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubsstate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
