# Generated by Django 3.2.5 on 2021-07-13 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stadiumsapp', '0001_initial'),
        ('clubsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='отделение')),
                ('football_field', models.CharField(default='единственное поле', max_length=32, verbose_name='Номер поля')),
                ('leagues', models.CharField(choices=[('Клубная Лига', 'Клубная Лига'), ('Первая Лига', 'Первая Лига'), ('Вторая Лига', 'Вторая Лига'), ('Третья Лига', 'Третья Лига'), ('Четвертая Лига', 'Четвертая Лига'), ('Пятая Лига', 'Пятая Лига'), ('Дивизион А', 'Дивизион А'), ('Дивизион Б', 'Дивизион Б')], default='Нет данных', max_length=32, verbose_name='Лига')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubsapp.clubs', verbose_name='Клуб')),
                ('place_of_match', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stadiumsapp.stadiums', verbose_name='Место проведения матчей')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'отделения',
            },
        ),
    ]
